services:
  agentic-hr:
    image: sameedkhatri/agentic-hr:v1.0.0
    container_name: agentic-hr
    ports:
      - "8501:8501"
      - "8080:8080"
    depends_on:
      - qdrant
    networks:
      - agentic-network

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-agentic-hr
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - agentic-network

networks:
  agentic-network:
    driver: bridge
